
api: 1.8.8
api-version: 1.8.8
name: 1v1Arena
main: me.didi.MainClass
author: didi
version: 0.0.1
description: LoL inspired Arena Fight Game
commands:
  project:
    desc: project main command
    usage: /project <subcommand>